FROM docker.elastic.co/beats/filebeat:7.5.0

USER root

# TODO if gid doesn't exist
#RUN groupadd -g 1 dockerhostgroup && usermod -a -G dockerhostgroup filebeat
#RUN usermod -a -G 1 filebeat

#USER filebeat
